# Generated by Django 6.0.4 on 2026-05-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbhi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('nin', models.CharField(max_length=14)),
                ('address', models.CharField(default='N/A', max_length=255)),
                ('dependents', models.IntegerField(default=0)),
                ('tenure_status', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='owner', max_length=20)),
                ('income_source', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_to_facility', models.FloatField(default=0.0)),
                ('risk_index', models.IntegerField(default=0, help_text='1-100 scale')),
                ('vulnerability_index', models.IntegerField(default=0, help_text='1-100 scale')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], default='mobile_money', max_length=20)),
                ('premium_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preferred_interview_date', models.DateField()),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('interviewed', 'Interviewed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_completed', models.BooleanField(default=False)),
                ('interview_date_conducted', models.DateField(blank=True, null=True)),
                ('income_bracket', models.CharField(blank=True, max_length=50, null=True)),
                ('survey_notes', models.TextField(blank=True, null=True)),
                ('cbhi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='cbhi.cbhi')),
            ],
        ),
    ]
