# Generated by Django 6.0.4 on 2026-05-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicant_latitude_alter_applicant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='illness_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='medical_burden',
            field=models.FloatField(default=0.0),
        ),
    ]
