# Generated by Django 6.0.4 on 2026-05-03 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBHI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Kivulu Health Shield', max_length=200)),
                ('community_name', models.CharField(max_length=200)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('admin_contact', models.CharField(blank=True, max_length=100)),
                ('target_members', models.IntegerField(default=0)),
                ('premium_per_person', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_annual_premium_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('SUSPENDED', 'Suspended')], default='PROPOSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'CBHI_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
